version: '3'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payloadpassword
      POSTGRES_DB: payload-cms
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cms:
    build: .
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URI=postgres://payload:payloadpassword@postgres:5432/payload-cms
      - PAYLOAD_SECRET=YOUR_SECRET_KEY_HERE
      - PAYLOAD_PUBLIC_SERVER_URL=http://localhost:3002
      - PORT=3000
    depends_on:
      - postgres
    volumes:
      - ./src:/home/node/app/src
      - ./uploads:/home/node/app/uploads
      - ./tsconfig.json:/home/node/app/tsconfig.json
    command: npm run dev

volumes:
  pgdata:
